/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#cdbdff",
        "tertiary-container": "#b55800",
        "on-primary-container": "#fcf6ff",
        "on-background": "#e6e0ee",
        "on-primary-fixed": "#20005f",
        "primary-container": "#7c4dff",
        "on-secondary-container": "#c0acff",
        "surface-container": "#211e28",
        "surface-container-highest": "#36333e",
        "surface-container-high": "#2b2833",
        "primary-fixed": "#e8deff",
        "on-tertiary": "#512400",
        "on-primary": "#370096",
        "inverse-on-surface": "#322f3a",
        "error-container": "#93000a",
        "surface": "#14121c",
        "on-tertiary-fixed": "#311300",
        "surface-dim": "#14121c",
        "secondary-fixed-dim": "#cdbdff",
        "primary": "#cdbdff",
        "on-secondary-fixed-variant": "#4c3989",
        "inverse-surface": "#e6e0ee",
        "on-secondary": "#352071",
        "primary-fixed-dim": "#cdbdff",
        "tertiary-fixed": "#ffdbc7",
        "tertiary-fixed-dim": "#ffb688",
        "on-primary-fixed-variant": "#4f00d0",
        "surface-variant": "#36333e",
        "surface-container-lowest": "#0f0d16",
        "on-tertiary-container": "#fff7f4",
        "on-surface": "#e6e0ee",
        "on-error": "#690005",
        "secondary": "#cdbdff",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#20025c",
        "surface-bright": "#3b3743",
        "secondary-container": "#4e3b8c",
        "secondary-fixed": "#e8deff",
        "outline": "#948ea1",
        "on-surface-variant": "#cac3d8",
        "error": "#ffb4ab",
        "background": "#14121c",
        "inverse-primary": "#6833ea",
        "tertiary": "#ffb688",
        "on-tertiary-fixed-variant": "#733600",
        "outline-variant": "#494455",
        "surface-container-low": "#1d1a24"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "margin-mobile": "16px",
        "xl": "32px",
        "sm": "8px",
        "margin-desktop": "32px",
        "base-unit": "4px",
        "lg": "24px",
        "gutter": "16px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
