# Generated by Django 6.1 on 2026-09-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('true_false', 'True/False'), ('fill_in', 'Fill in the gap'), ('applies', 'Select All That Apply')], max_length=20),
        ),
    ]
