# Generated by Django 6.1.1 on 2026-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_dailystudylog_questionschedule_delete_reviewattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionschedule',
            options={'ordering': ['scheduled_date']},
        ),
        migrations.RenameField(
            model_name='dailystudylog',
            old_name='goal_met',
            new_name='creation_streak_met',
        ),
        migrations.RenameField(
            model_name='questionschedule',
            old_name='repetitions',
            new_name='review_count',
        ),
        migrations.RenameField(
            model_name='questionschedule',
            old_name='due_date',
            new_name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='questionschedule',
            name='ease_factor',
        ),
        migrations.RemoveField(
            model_name='questionschedule',
            name='interval',
        ),
        migrations.AddField(
            model_name='dailystudylog',
            name='review_streak_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionschedule',
            name='mastered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionschedule',
            name='streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
