# Generated by Django 6.1.1 on 2026-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_replace_sm2_with_custom_srs'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionschedule',
            name='available_at',
            field=models.DateTimeField(blank=True, help_text='Used for intra-session minute delays', null=True),
        ),
    ]
