# Generated by Django 6.1.1 on 2026-09-26 00:57

from django.db import migrations
from django.utils import timezone

def reset_due_dates_to_today(apps, schema_editor):
    QuestionSchedule = apps.get_model('quiz', 'QuestionSchedule')
    today = timezone.localdate()
    # Update all existing schedules so their due date is today
    QuestionSchedule.objects.update(scheduled_date=today)

def reverse_reset(apps, schema_editor):
    # No obvious way to reverse this lossy operation.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questionschedule_available_at'),
    ]

    operations = [
        migrations.RunPython(reset_due_dates_to_today, reverse_code=reverse_reset),
    ]
