# Generated by Django 6.1 on 2026-08-22 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='materials/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('block_type', models.CharField(choices=[('heading_1', 'Heading 1'), ('heading_2', 'Heading 2'), ('heading_3', 'Heading 3'), ('paragraph', 'Paragraph'), ('list_item', 'List Item')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.block')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='documents.material')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('material', 'parent', 'order')},
            },
        ),
    ]
